# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'project2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project2
  pod 'Toast'
  pod 'SDWebImage'
  
end
